version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pokedex-db
    restart: always
    environment:
      POSTGRES_USER: pokedex_user
      POSTGRES_PASSWORD: pokedex_pass
      POSTGRES_DB: pokedex
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pokedex_network

volumes:
  postgres_data:

networks:
  pokedex_network:
